<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('users')->insert([

            // ── ADMIN ────────────────────────────────────────────────────────
            [
                'id'                => 1,
                'last_name'         => 'Navarro',
                'first_name'        => 'Marco',
                'middle_name'       => 'Santos',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => null,
                'real_name'         => null,
                'teacher_type'      => null,
                'position'          => null,
                'email'             => 'admin@mn2coworking.com',
                'phone_number'      => '09171234001',
                'password'          => Hash::make('Admin@1234'),
                'role'              => 'admin',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── TEAM LEADERS ─────────────────────────────────────────────────
            [
                'id'                => 2,
                'last_name'         => 'Reyes',
                'first_name'        => 'Angela',
                'middle_name'       => 'Cruz',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => null,
                'real_name'         => null,
                'teacher_type'      => null,
                'position'          => null,
                'email'             => 'angela.reyes@mn2coworking.com',
                'phone_number'      => '09181234002',
                'password'          => Hash::make('Leader@1234'),
                'role'              => 'team_leader',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 3,
                'last_name'         => 'Dela Cruz',
                'first_name'        => 'Ramon',
                'middle_name'       => 'Lim',
                'suffix'            => 'Jr.',
                'profile_photo_path'=> null,
                'teacher_id'        => null,
                'real_name'         => null,
                'teacher_type'      => null,
                'position'          => null,
                'email'             => 'ramon.delacruz@mn2coworking.com',
                'phone_number'      => '09191234003',
                'password'          => Hash::make('Leader@1234'),
                'role'              => 'team_leader',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 4,
                'last_name'         => 'Mendoza',
                'first_name'        => 'Patricia',
                'middle_name'       => 'Garcia',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => null,
                'real_name'         => null,
                'teacher_type'      => null,
                'position'          => null,
                'email'             => 'patricia.mendoza@mn2coworking.com',
                'phone_number'      => '09201234004',
                'password'          => Hash::make('Leader@1234'),
                'role'              => 'team_leader',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── TEACHERS ─────────────────────────────────────────────────────
            [
                'id'                => 5,
                'last_name'         => 'Santos',
                'first_name'        => 'Maria',
                'middle_name'       => 'Flores',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => 'TCH-2024-001',
                'real_name'         => 'Ana Kristine Reyes',
                'teacher_type'      => 'domestic',
                'position'          => null,
                'email'             => 'maria.santos@mn2coworking.com',
                'phone_number'      => '09211234005',
                'password'          => Hash::make('Teacher@1234'),
                'role'              => 'teacher',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 6,
                'last_name'         => 'Torres',
                'first_name'        => 'Jose',
                'middle_name'       => 'Bautista',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => 'TCH-2024-002',
                'real_name'         => 'Roberto Miguel Dela Cruz',
                'teacher_type'      => 'overseas',
                'position'          => null,
                'email'             => 'jose.torres@mn2coworking.com',
                'phone_number'      => '09221234006',
                'password'          => Hash::make('Teacher@1234'),
                'role'              => 'teacher',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 7,
                'last_name'         => 'Villanueva',
                'first_name'        => 'Clarissa',
                'middle_name'       => 'Ong',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => 'TCH-2024-003',
                'real_name'         => 'Patricia Jomarie Tan',
                'teacher_type'      => 'domestic',
                'position'          => null,
                'email'             => 'clarissa.villanueva@mn2coworking.com',
                'phone_number'      => '09231234007',
                'password'          => Hash::make('Teacher@1234'),
                'role'              => 'teacher',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── STAFF ────────────────────────────────────────────────────────
            [
                'id'                => 8,
                'last_name'         => 'Garcia',
                'first_name'        => 'Liza',
                'middle_name'       => 'Bautista',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => null,
                'real_name'         => null,
                'teacher_type'      => null,
                'position'          => 'Operations Staff',
                'email'             => 'liza.garcia@mn2coworking.com',
                'phone_number'      => '09241234008',
                'password'          => Hash::make('Staff@1234'),
                'role'              => 'staff',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 9,
                'last_name'         => 'Aquino',
                'first_name'        => 'Rodel',
                'middle_name'       => 'Macaraeg',
                'suffix'            => null,
                'profile_photo_path'=> null,
                'teacher_id'        => null,
                'real_name'         => null,
                'teacher_type'      => null,
                'position'          => 'Administrative Staff',
                'email'             => 'rodel.aquino@mn2coworking.com',
                'phone_number'      => '09251234009',
                'password'          => Hash::make('Staff@1234'),
                'role'              => 'staff',
                'is_active'         => true,
                'email_verified_at' => $now,
                'remember_token'    => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ]);
    }
}